language: java

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - nodejs

install:
 - npm install deploy/

jdk:
  - oraclejdk8

branches:
  only:
  - backend

script:
 - mvn -f proglev/client/pom.xml clean install
 - node deploy\deployToGoogleDrive.js